"""add_liste_contacts_table

Revision ID: 11952268b8d5
Revises: a123b456c789
Create Date: 2025-09-08 05:26:09.673246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11952268b8d5'
down_revision: Union[str, Sequence[str], None] = 'a123b456c789'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('liste_contacts',
    sa.Column('id_liste', sa.Integer(), nullable=False),
    sa.Column('id_contact', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['id_contact'], ['contacts.id_contact'], ),
    sa.ForeignKeyConstraint(['id_liste'], ['mailing_lists.id_liste'], ),
    sa.PrimaryKeyConstraint('id_liste', 'id_contact')
    )
    op.drop_index('idx_activity_logs_timestamp', table_name='activity_logs')
    op.drop_index('idx_activity_logs_user', table_name='activity_logs')
    op.drop_index('ix_agents_id_agent', table_name='agents')
    op.drop_index('idx_campagnes_date_debut', table_name='campagnes')
    op.drop_index('idx_campagnes_statut', table_name='campagnes')
    op.drop_index('ix_campagnes_id_agent', table_name='campagnes')
    op.drop_index('ix_campagnes_id_campagne', table_name='campagnes')
    op.drop_constraint('campagnes_id_agent_fkey', 'campagnes', type_='foreignkey')
    op.drop_constraint('campagnes_id_modele_fkey', 'campagnes', type_='foreignkey')
    op.create_foreign_key(None, 'campagnes', 'message_templates', ['id_modele'], ['id_modele'])
    op.create_foreign_key(None, 'campagnes', 'agents', ['id_agent'], ['id_agent'])
    op.drop_constraint('campaign_reports_id_campagne_fkey', 'campaign_reports', type_='foreignkey')
    op.create_foreign_key(None, 'campaign_reports', 'campagnes', ['id_campagne'], ['id_campagne'])
    op.drop_index('idx_contacts_opt_in', table_name='contacts')
    op.drop_index('idx_contacts_segment', table_name='contacts')
    op.drop_index('idx_contacts_zone', table_name='contacts')
    op.drop_index('ix_contacts_numero_telephone', table_name='contacts')
    op.alter_column('mailing_lists', 'id_campagne',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('mailing_lists_id_campagne_fkey', 'mailing_lists', type_='foreignkey')
    op.create_foreign_key(None, 'mailing_lists', 'campagnes', ['id_campagne'], ['id_campagne'])
    op.drop_index('idx_messages_campaign', table_name='messages')
    op.drop_index('idx_messages_date', table_name='messages')
    op.drop_index('idx_messages_status', table_name='messages')
    op.drop_index('ix_messages_date_envoi', table_name='messages')
    op.drop_index('ix_messages_id_campagne', table_name='messages')
    op.drop_index('ix_messages_statut_livraison', table_name='messages')
    op.drop_constraint('messages_id_liste_fkey', 'messages', type_='foreignkey')
    op.drop_constraint('messages_id_contact_fkey', 'messages', type_='foreignkey')
    op.drop_constraint('messages_id_campagne_fkey', 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'campagnes', ['id_campagne'], ['id_campagne'])
    op.create_foreign_key(None, 'messages', 'contacts', ['id_contact'], ['id_contact'])
    op.create_foreign_key(None, 'messages', 'mailing_lists', ['id_liste'], ['id_liste'])
    op.alter_column('sms_queue', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('sms_queue', 'attempts',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_index('idx_sms_queue_campaign', table_name='sms_queue')
    op.drop_index('idx_sms_queue_scheduled', table_name='sms_queue')
    op.drop_index('idx_sms_queue_status', table_name='sms_queue')
    op.drop_constraint('sms_queue_contact_id_fkey', 'sms_queue', type_='foreignkey')
    op.drop_constraint('sms_queue_campaign_id_fkey', 'sms_queue', type_='foreignkey')
    op.create_foreign_key(None, 'sms_queue', 'contacts', ['contact_id'], ['id_contact'])
    op.create_foreign_key(None, 'sms_queue', 'campagnes', ['campaign_id'], ['id_campagne'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sms_queue', type_='foreignkey')
    op.drop_constraint(None, 'sms_queue', type_='foreignkey')
    op.create_foreign_key('sms_queue_campaign_id_fkey', 'sms_queue', 'campagnes', ['campaign_id'], ['id_campagne'], ondelete='CASCADE')
    op.create_foreign_key('sms_queue_contact_id_fkey', 'sms_queue', 'contacts', ['contact_id'], ['id_contact'], ondelete='CASCADE')
    op.create_index('idx_sms_queue_status', 'sms_queue', ['status'], unique=False)
    op.create_index('idx_sms_queue_scheduled', 'sms_queue', ['scheduled_at'], unique=False)
    op.create_index('idx_sms_queue_campaign', 'sms_queue', ['campaign_id'], unique=False)
    op.alter_column('sms_queue', 'attempts',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('sms_queue', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key('messages_id_campagne_fkey', 'messages', 'campagnes', ['id_campagne'], ['id_campagne'], ondelete='CASCADE')
    op.create_foreign_key('messages_id_contact_fkey', 'messages', 'contacts', ['id_contact'], ['id_contact'], ondelete='CASCADE')
    op.create_foreign_key('messages_id_liste_fkey', 'messages', 'mailing_lists', ['id_liste'], ['id_liste'], ondelete='CASCADE')
    op.create_index('ix_messages_statut_livraison', 'messages', ['statut_livraison'], unique=False)
    op.create_index('ix_messages_id_campagne', 'messages', ['id_campagne'], unique=False)
    op.create_index('ix_messages_date_envoi', 'messages', ['date_envoi'], unique=False)
    op.create_index('idx_messages_status', 'messages', ['statut_livraison'], unique=False)
    op.create_index('idx_messages_date', 'messages', ['date_envoi'], unique=False)
    op.create_index('idx_messages_campaign', 'messages', ['id_campagne'], unique=False)
    op.drop_constraint(None, 'mailing_lists', type_='foreignkey')
    op.create_foreign_key('mailing_lists_id_campagne_fkey', 'mailing_lists', 'campagnes', ['id_campagne'], ['id_campagne'], ondelete='CASCADE')
    op.alter_column('mailing_lists', 'id_campagne',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index('ix_contacts_numero_telephone', 'contacts', ['numero_telephone'], unique=False)
    op.create_index('idx_contacts_zone', 'contacts', ['zone_geographique'], unique=False)
    op.create_index('idx_contacts_segment', 'contacts', ['segment'], unique=False)
    op.create_index('idx_contacts_opt_in', 'contacts', ['statut_opt_in'], unique=False)
    op.drop_constraint(None, 'campaign_reports', type_='foreignkey')
    op.create_foreign_key('campaign_reports_id_campagne_fkey', 'campaign_reports', 'campagnes', ['id_campagne'], ['id_campagne'], ondelete='CASCADE')
    op.drop_constraint(None, 'campagnes', type_='foreignkey')
    op.drop_constraint(None, 'campagnes', type_='foreignkey')
    op.create_foreign_key('campagnes_id_modele_fkey', 'campagnes', 'message_templates', ['id_modele'], ['id_modele'], ondelete='SET NULL')
    op.create_foreign_key('campagnes_id_agent_fkey', 'campagnes', 'agents', ['id_agent'], ['id_agent'], ondelete='CASCADE')
    op.create_index('ix_campagnes_id_campagne', 'campagnes', ['id_campagne'], unique=False)
    op.create_index('ix_campagnes_id_agent', 'campagnes', ['id_agent'], unique=False)
    op.create_index('idx_campagnes_statut', 'campagnes', ['statut'], unique=False)
    op.create_index('idx_campagnes_date_debut', 'campagnes', ['date_debut'], unique=False)
    op.create_index('ix_agents_id_agent', 'agents', ['id_agent'], unique=False)
    op.create_index('idx_activity_logs_user', 'activity_logs', ['user_id'], unique=False)
    op.create_index('idx_activity_logs_timestamp', 'activity_logs', ['timestamp'], unique=False)
    op.drop_table('liste_contacts')
    # ### end Alembic commands ###
