"""Add soft delete to mailing lists and add indexes

Revision ID: 64f3934e4aa6
Revises: 4135d03468b3
Create Date: 2025-09-02 22:02:22.585141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64f3934e4aa6'
down_revision: Union[str, Sequence[str], None] = '4135d03468b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mailing_lists', sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True))
    op.create_index('idx_liste_contacts_list_contact', 'liste_contacts', ['id_liste', 'id_contact'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_liste_contacts_list_contact', table_name='liste_contacts')
    op.drop_column('mailing_lists', 'deleted_at')
    # ### end Alembic commands ###
